#!/usr/bin/python2
import os
from subprocess import call,check_output,check_call

def ComposeFiles2Str(dirname):
	srcs = check_output("ls ./"+dirname,shell=True)
	srcss = srcs.split("\n")
	aggstr = ""
	for src in srcss:
        	if src!="":
                	aggstr+=" "+dirname+"/"+src
	return aggstr

aggstr = ComposeFiles2Str("src")
aggstr2 = ComposeFiles2Str("include")
	
print "PREPARE FOR BUILDING..."
print "OGRE_ROOT=",os.environ['OGRE_ROOT']
print "ANDROID_NDK=",os.environ['ANDROID_NDK']
print "LOCAL_PATH",os.environ['LOCAL_PATH']
print "GAINPUT_PATH",os.environ['GAINPUT_PATH']

projn = os.environ['PROJECT_NAME']
ogrt = os.environ['OGRE_ROOT']
andn = os.environ['ANDROID_NDK']
andb = os.environ['ANDROID_BUILD']
arme = os.environ['ARMEABI']
pwdpath = os.environ['LOCAL_PATH']
arch = os.environ['ARCH']
apil = os.environ['API_LEVEL']
projo = os.environ['PROJECT_PACKAGE']
gainput = os.environ['GAINPUT_PATH']

mkin = open("android/jni/Android.mk.in","r")
mkind = mkin.read()

mkind = mkind.replace("@OGRE_ROOT",ogrt)
mkind = mkind.replace("@ANDROID_NDK_ROOT",andn)
mkind = mkind.replace("@LOCAL_PATH",pwdpath)
mkind = mkind.replace("@ANDROID_BUILD",andb)
mkind = mkind.replace("@ARMEABI",arme)
mkind = mkind.replace("@SRC",aggstr)
mkind = mkind.replace("@PROJECT_NAME",projn)
mkind = mkind.replace("@PROJECT_PACKAGE",projo)
mkind = mkind.replace("@GAINPUT_PATH",gainput)

mk = open("android/jni/Android.mk","w")
mk.write(mkind)

appin = open("android/AndroidManifest.xml.in","r")
appind = appin.read()
appind = appind.replace("@PROJECT_NAME",projn)
appind = appind.replace("@PROJECT_PACKAGE",projo)

appio = open("android/AndroidManifest.xml","w")
appio.write(appind)

print 'Change directory=',check_call("cd android", shell=True)
print 'Update android project=',check_call("cd android; android update project -t 1 -p . -s", shell=True)
#print 'NDK-build=',check_call("cd android; ndk-build",shell=True)
#print 'Ant install=',check_call("cd android; ant debug install",shell=True)

#Generate CMakeLists.txt 
cmakel = open("CMakeLists.txt","w")
cmakel.write("cmake_minimum_required(VERSION 2.8)\n")
cmakel.write("project("+projn+")\n")
cmakel.write("add_executable(par "+aggstr+" "+aggstr2+")\n")

#Compose include for android-ndk
incs = "include_directories("+andn+"/platforms/android-"+apil+"/arch-"+arch+"/usr/include)\n"
incs2 = "include_directories("+ogrt+"/OgreMain/include )\n"
incs3 = "include_directories("+pwdpath+"/include )\n"
incs4 = "include_directories("+andn+"/sources/android/native_app_glue/ )\n"
incs5 = "include_directories("+gainput+"/lib/include/ )\n"
cmakel.write(incs)
cmakel.write(incs2)
cmakel.write(incs3)
cmakel.write(incs4)
cmakel.write(incs5)

for comp in ["RTShaderSystem","Overlay","Property"]:
	cmakel.write("include_directories("+ogrt+"/Components/"+comp+"/include )\n")
